---
title: "Introducción al Cómputo de Alto Rendimiento (HPC)"
---

[← Volver a Tutoriales](tutoriales.qmd)

**Día y horario:**
Martes 25 de Agosto

- 7:00 hs México (UTC-6)
- 8:00 hs Perú (UTC-5)
- 9:00 hs Chile (UTC-4)
- 10:00 hs Argentina (UTC-3)

Podés consultar en tu hora local con este link: [https://everytimezone.com/s/62d760a3](https://everytimezone.com/s/62d760a3)

**Duración:** 2 horas

**Instructora:** Maëlle Salmon ([GitHub](https://github.com/maelle) | [Personal website](https://masalmon.eu/))

<details class="bio-toggle">
<summary>Ver mini biografía</summary>

Maëlle Salmon es doctora en estadística e ingeniera en software de R e investigación. Trabaja en rOpenSci, creó el blog de R-hub y coescribió el libro HTTP testing in R junto a Scott Chamberlain. Además, es miembro del equipo global de R-Ladies+ y colabora activamente en el desarrollo de herramientas para la comunidad de R. Enseña Git de forma regular desde hace meses, incluso este mismo tutorial en R en Buenos Aires + R-Ladies Santa Rosa. Creó el paquete {saperlipopette} para poder mostrar y compartir ejercicios de Git.

</details>

**Link de inscripción:** [a completar]()

---

## Descripción

Git es muy útil, por cierto. Pero también puede ser escalofriante cuando cometemos un error. Por suerte, con experiencia cometemos menos errores… y/o sabemos mejor cómo corregirlas! En este taller práctico aprenderemos a salir de siete posibles situaciones de mier…coles que pueden ocurrirse, con siete ejercicios inspirados del sitio web Oh Shit, Git! y proporcionados por el paquete R {saperlipopette}. Al final de este taller, nos sentiremos más capaces de enfrentarnos a Git y a nuestra propia falibilidad.

## A quién está dirigido

Este taller está orientado a personas que ya tienen alguna experiencia usando control de versiones, aunque no hace falta ser experto o experta. Ideal para quienes quieren fortalecer su confianza y autonomía frente a situaciones difíciles.

## Prerrequisitos

Para participar necesitarán una computadora con conexión a internet. Experiencia previa básica con Git y control de versiones es recomendable.

**Duración:** 2 horas


---

[← Volver a Tutoriales](tutoriales.qmd)
