---
title: "Cómo integrar LLM en nuestro flujo de trabajo con R"
---

[← Volver a Tutoriales](tutoriales.qmd)

**Día y horario:**
Viernes 28 de agosto

- 8:00 hs México (UTC-6)
- 9:00 hs Perú (UTC-5)
- 10:00 hs Chile (UTC-4)
- 11:00 hs Argentina (UTC-3)

[Consulta tu hora local](https://everytimezone.com/s/62d760a3)

**Duración:** 2 horas

**Instructor:** Luis D. Verde Arregoitia ([GitHub](https://github.com/luisDVA) | [Personal website](https://liomys.mx/))

<details class="bio-toggle">
<summary>Ver bio</summary>

Luis D. Verde Arregoitia es doctor en ciencias y biológicas, especialista en mamíferos, y actualmente trabaja como científico de datos de biodiversidad en el Instituto de Ecología A.C. (INECOL) en Xalapa, México. Escribió y mantiene la guía en línea de [Herramientas para usar modelos de lenguaje de gran escala (LLM) en R](https://luisdva.github.io/llmsr-book/es/index.es.html). Es mentor en el programa de campeones y campeonas de rOpenSci, y le interesa enseñar sobre el uso eficiente y responsable de implementaciones de inteligencia artificial en tareas de datos en R.

</details>

[Registro](https://www.eventbrite.com/e/rsla26-research-software-latinoamerica-tickets-1995193038086){.btn .btn-primary}

---

## Descripción

Los Modelos de Lenguaje de Gran Escala (LLMs) son cada vez más capaces de escribir, explicar y depurar código en R. Al mismo tiempo, se desarrollan y mejoran continuamente nuevas herramientas que integran estos modelos directamente en nuestros entornos de desarrollo.

Este taller práctico presenta el ecosistema moderno de herramientas basadas en LLMs disponibles para R. Las personas participantes aprenderán a incorporar estas herramientas en sus flujos de trabajo de procesamiento, visualización y análisis de datos en R, logrando procesos más ágiles, eficientes y productivos.

## A quién está dirigido

Se requieren conocimientos básicos de programación en R. No es necesario contar con experiencia previa en el uso de modelos de lenguaje (LLMs).

## Objetivos de aprendizaje

Al finalizar el taller, las personas participantes serán capaces de:

- Entender las diferencias entre modelos, proveedores, y las herramientasas que comunican LLM con entordos de programación. 
- Integrar herramientas basadas en LLMs en flujos de trabajo de análisis de datos con R.
- Generar, editar, documentar y depurar código en R de manera rápida y precisa.
- Interactuar con las APIs de modelos de lenguaje desde la consola de R y desde su entorno de desarrollo integrado (IDE) preferido.

**Duración:** 2 horas

[Registro](https://www.eventbrite.com/e/rsla26-research-software-latinoamerica-tickets-1995193038086){.btn .btn-primary}

---

[← Volver a Tutoriales](tutoriales.qmd)
