---
title: "¡Miércoles, Git! Manejo de errores en Git y no morir en el intento"
---

[← Volver a Tutoriales](tutoriales.qmd)

**Día y horario:**
Martes 25 de agosto

- 7:00 hs México (UTC-6)
- 8:00 hs Perú (UTC-5)
- 9:00 hs Chile (UTC-4)
- 10:00 hs Argentina (UTC-3)

[Consulta tu hora local](https://everytimezone.com/s/62d760a3)

**Duración:** 2 horas

**Instructoras:** Maëlle Salmon ([GitHub](https://github.com/maelle) | [Personal website](https://masalmon.eu/)) y Yanina Bellini Saibene ([GitHub](https://github.com/yabellini) | [Personal website](https://yabellini.netlify.app/))

<details class="bio-toggle">
<summary>Ver mini biografía</summary>

Maëlle Salmon es doctora en estadística e ingeniera en software de R e investigación. Trabaja en rOpenSci, creó el blog de R-hub y coescribió el libro HTTP testing in R junto a Scott Chamberlain. Además, es miembro del equipo global de R-Ladies+ y colabora activamente en el desarrollo de herramientas para la comunidad de R. Enseña Git de forma regular desde hace meses, incluso este mismo tutorial en R en Buenos Aires + R-Ladies Santa Rosa. Creó el paquete {saperlipopette} para poder mostrar y compartir ejercicios de Git.

Yanina Bellini Saibene es magíster en minería de datos y gestión del conocimiento. Trabaja en rOpenSci y es Fellow 2026 de la Agencia de Soberanía Tecnológica de Alemania. Es profesora de la Universidad Austral (Argentina) y forma parte del directorio de RLadies+ y de The Carpentries. También es una GitHub Star y enseña Git y GitHub desde hace 8 años.

</details>

Al completar el [registro para la conferencia](https://www.eventbrite.com/e/rsla26-research-software-latinoamerica-tickets-1995193038086), podrás seleccionar los tutoriales en los que desees participar. La inscripción es flexible: puedes elegir un único tutorial o tantos como sean de tu interés.

Los tutoriales tienen un costo de inscripción, que varía según la categoría del participante. 

- Estudiantes de tiempo completo: US$ 7  por tutorial
- Academia (investigadores, docentes, etc.): US$ 10 por tutorial
- Industria: US$ 15 por tutorial

Los fondos recaudados nos ayudan a cubrir los costos asociados a la organización del evento.

[Registro](https://www.eventbrite.com/e/rsla26-research-software-latinoamerica-tickets-1995193038086){.btn .btn-primary}

---

## Descripción

Git es muy útil, por cierto. Pero también puede ser escalofriante cuando cometemos un error. Por suerte, con experiencia cometemos menos errores… y/o sabemos mejor cómo corregirlas! En este taller práctico aprenderemos a salir de siete posibles situaciones de mier…coles que pueden ocurrirse, con siete ejercicios inspirados del sitio web Oh Shit, Git! y proporcionados por el paquete R {saperlipopette}. Al final de este taller, nos sentiremos más capaces de enfrentarnos a Git y a nuestra propia falibilidad.

## A quién está dirigido

Este taller está orientado a personas que ya tienen alguna experiencia usando control de versiones, aunque no hace falta ser experto o experta. Ideal para quienes quieren fortalecer su confianza y autonomía frente a situaciones difíciles.

## Prerrequisitos

- Computadora personal para hacer los ejercicios (puede ser diferente de la que usás para conectarte al curso, solo que en este caso no se podrá compartir la pantalla en caso de problema).
- Tener Git instalado en la computadora: <https://happygitwithr.com/install-git> y <https://happygitwithr.com/hello-git>.
- Ya usar Git un poco (`git commit`, `git pull`/`push`, ramas, GitHub u otra plataforma). Si querés repasar un poco, te recomendamos el workshop <https://yabellini.netlify.app/courses/git_rstudio_course/>.
- Instalar {saperlipopette} en tu computadora:

  ```r
  install.packages(
    "saperlipopette",
    repos = c("https://packages.ropensci.org", "https://cloud.r-project.org")
  )
  ```

  Más información en <https://docs.ropensci.org/saperlipopette/>.
- Si querés, instalá Positron, pero los ejercicios se pueden hacer en RStudio o con tus herramientas usuales para R y Git.

**Duración:** 2 horas

[Registro](https://www.eventbrite.com/e/rsla26-research-software-latinoamerica-tickets-1995193038086){.btn .btn-primary}

---

[← Volver a Tutoriales](tutoriales.qmd)
